---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rabbit-pod-autoscaler
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rabbit-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit-pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: rabbit-pod-autoscaler
    namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbit-pod-autoscaler
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: ec2.amazonaws.com/type
                operator: In
                values:
                - core
      serviceAccountName: rabbit-pod-autoscaler
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: core
      containers:
        - name: rabbit-pod-autoscaler
          image: onfido/k8s-rabbit-pod-autoscaler
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 200Mi
          env:
            - name: INTERVAL
              value: "30"
            - name: RABBIT_HOST
              value: "http://rmq-mgmt.default"
            #- name: RABBIT_USER
              #valueFrom:
                #secretKeyRef:
                  #name: rabbit-pod-autoscaler
                  #key: rabbit-user
            - name: RABBIT_PASS
              #valueFrom:
                #secretKeyRef:
                  #name: rabbit-pod-autoscaler
                  #key: rabbit-pass
            - name: RABBIT_USER
              value: "esio"
            - name: RABBIT_PASS
              value: "esio"
            - name: AUTOSCALING
              value: >
                1|10|30|default|reader-deployment|build;
            - name: LOGS
              value: HIGH
            - name: SLACK_HOOK
              value: SLACK_HOOK
